// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZouoflH2cgTcb_QGp2Y90KN1nsw7ELiI',
    appId: '1:63187147307:web:d84030bbdbdc9ef397e86e',
    messagingSenderId: '63187147307',
    projectId: 'productlistingapp-2e5dc',
    authDomain: 'productlistingapp-2e5dc.firebaseapp.com',
    storageBucket: 'productlistingapp-2e5dc.firebasestorage.app',
    measurementId: 'G-FVENEXD6V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhCXhbxcROVleWKHwzOOTmEzDsfBqBAW4',
    appId: '1:63187147307:android:fe98e24644ba343597e86e',
    messagingSenderId: '63187147307',
    projectId: 'productlistingapp-2e5dc',
    storageBucket: 'productlistingapp-2e5dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbvTU12VNWR35xm8Onun-v7ksPpSDl3HY',
    appId: '1:63187147307:ios:2ac9589c088d786697e86e',
    messagingSenderId: '63187147307',
    projectId: 'productlistingapp-2e5dc',
    storageBucket: 'productlistingapp-2e5dc.firebasestorage.app',
    iosBundleId: 'com.example.productListingApp',
  );
}
